# docker-compose.yml

version: "3.5"
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    networks:
      - app-tier
    depends_on:
      - db
    links:
      - db
  db:
    image: mysql:8.0.29
    platform: linux/x86_64
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    #volumes:
    #  - ./db/init:/docker-entrypoint-initdb.d
    #  - ./db/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    networks:
      - app-tier
    ports:
      - "3306:3306"
    expose:
      - "3306"

networks:
  app-tier:
    driver: bridge